INSERT INTO TipoViolazione1 (Descrizione)
VALUES 
('Eccesso di velocità'),
('Attraversamento col semaforo rosso'),
('Guida senza cintura di sicurezza'),
('Utilizzo del telefono cellulare alla guida'),
('Mancato rispetto della segnaletica stradale'),
('Guida in stato di ebbrezza'),
('Sorpasso vietato'),
('Mancato uso delle frecce direzionali'),
('Sosta in divieto di fermata'),
('Guida senza patente'),
('Veicolo non revisionato'),
('Manutenzione non adeguata del veicolo'),
('Guida contromano'),
('Guida senza assicurazione'),
('Eccesso di velocità in autostrada'),
('Sosta in zona pedonale'),
('Occupazione abusiva di suolo pubblico'),
('Manca segnalazione autovelox'),
('Veicolo inquinante'),
('Mancato soccorso in caso di incidente'),
('Manutenzione non adeguata dei pneumatici'),
('Manutenzione non adeguata dei freni'),
('Veicolo senza revisione periodica'),
('Conducente senza casco'),
('Mancata omologazione del veicolo'),
('Guida senza allacciare la cintura ai minori'),
('Manca il kit di pronto soccorso'),
('Guida con tasso alcolemico superiore al consentito'),
('Manca il gilet catarifrangente'),
('Guida senza documenti di guida'),
('Veicolo senza copertura assicurativa'),
('Manca il libretto di circolazione'),
('Guida senza la luce di posizione accesa'),
('Sosta in doppia fila'),
('Guida con targa non conforme'),
('Veicolo senza specchietti retrovisori'),
('Mancato rispetto della precedenza'),
('Manca il certificato di conformità'),
('Veicolo con targa coperta'),
('Sosta in area pedonale'),
('Trasporto di animali senza gabbia adeguata'),
('Manca il seggiolino per bambini'),
('Guida con il cellulare in mano'),
('Veicolo senza indicatori di direzione funzionanti'),
('Manca la revisione del serbatoio gas');

